// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB11ogDWTxOOISvzkV2P0lGhzApn6QiNk8',
    appId: '1:496213153614:web:4a524d2d8a742f190ef01f',
    messagingSenderId: '496213153614',
    projectId: 'metabilim-4ef76',
    authDomain: 'metabilim-4ef76.firebaseapp.com',
    storageBucket: 'metabilim-4ef76.firebasestorage.app',
    measurementId: 'G-EL34621VXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnd3uvz4P5Y9cxhbAMm4NEh-GQHRLTL-w',
    appId: '1:496213153614:android:2907b604b14520090ef01f',
    messagingSenderId: '496213153614',
    projectId: 'metabilim-4ef76',
    storageBucket: 'metabilim-4ef76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5LIqUH6A37pYlTzyQ0PMvhMZZ6xT1NmA',
    appId: '1:496213153614:ios:63468af8b0a0836e0ef01f',
    messagingSenderId: '496213153614',
    projectId: 'metabilim-4ef76',
    storageBucket: 'metabilim-4ef76.firebasestorage.app',
    iosBundleId: 'com.example.metabilim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5LIqUH6A37pYlTzyQ0PMvhMZZ6xT1NmA',
    appId: '1:496213153614:ios:63468af8b0a0836e0ef01f',
    messagingSenderId: '496213153614',
    projectId: 'metabilim-4ef76',
    storageBucket: 'metabilim-4ef76.firebasestorage.app',
    iosBundleId: 'com.example.metabilim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB11ogDWTxOOISvzkV2P0lGhzApn6QiNk8',
    appId: '1:496213153614:web:da09cc61bbe6e0d40ef01f',
    messagingSenderId: '496213153614',
    projectId: 'metabilim-4ef76',
    authDomain: 'metabilim-4ef76.firebaseapp.com',
    storageBucket: 'metabilim-4ef76.firebasestorage.app',
    measurementId: 'G-GVSQ2LL5LK',
  );
}
